engines:
  duplication:
    enabled: true
    config:
      languages:
      - C++
      - Cypher
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "Utils/include/*.hpp"
  - "Utils/src/*.hpp"
  - "Utils/src/*.cpp"
  - "TrainProvider/include/*.hpp"
  - "TrainProvider/src/*.hpp"
  - "TrainProvider/src/*.cpp"
  - "Server/src/*.hpp"
  - "Server/src/*.cpp"
  - "Server/include/*.hpp"
exclude_paths: ["TrainProvider_test/", "lib/", "database-*/", "Client/", "*.txt", "CMakeLists/", "*.yml", "docs/"]
